### ISSUE TITLE
Some notes on your Gnome title bar article ...

### ISSUE THREAD

**Issue by farblos** [joshtronic/dotfiles#27]
No twitter here, so this is as close as I could get to your article https://joshtronic.com/2017/07/26/hide-title-bars-in-gnome-shell/ ... feel free to close this issue without further ado.

Your article helped me to get rid of my SSD title bars easily (thanks).  But then I felt that I *must* understand that logic how SSD window decorations are actually built or otherwise I would not feel happy anymore.

So here is my now-minimal `gtk.css` including some (hopefully helpful) comments:

``` css
/*
 * Some information on the decoration of SSD windows:
 *
 * - Mutter collects the style information for the decoration of
 *   SSD windows in structure "MetaStyleInfo" using function
 *   "meta_theme_create_style_info" from "src/ui/theme.c".
 *
 * - That function builds a hard-coded style hierarchy and
 *   equally hard-coded style classes along the lines of:
 *
 *     window           [.background|.ssd]                              META_STYLE_ELEMENT_WINDOW
 *       decoration                                                     META_STYLE_ELEMENT_FRAME
 *         headerbar    [.titlebar|.horizontal|.default-decoration]     META_STYLE_ELEMENT_TITLEBAR
 *           label      [.title]                                        META_STYLE_ELEMENT_TITLE
 *           button     [.titlebutton]                                  META_STYLE_ELEMENT_BUTTON
 *             image                                                    META_STYLE_ELEMENT_IMAGE
 *
 * - The information from that style hierarchy is then used by
 *   the various functions in "src/ui/theme.c" to calculate the
 *   frame dimensions and draw it.
 */

/* switch off border rounding of SSD windows */
window.ssd > decoration {
  border-radius: 0;
}

/* hide title bar of SSD windows */
window.ssd > decoration > headerbar {
  border: 0;
  padding: 0;
  border-radius: 0;
  min-height: 0;
}

/* hide window title and buttons of SSD windows.  Their height
 * cannot be changed by any styles, so that margin-cludge is
 * needed. */
window.ssd > decoration > headerbar > label,
window.ssd > decoration > headerbar > button {
  margin-top: -100px;
}
```

Running on Gnome version 3.38.5, BTW.
